version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: dockerfile
    user: "node"
    env_file:
      - ".github.token.env"
    volumes:
      - ../:/devcontainer:cached
